import type { Blueprint } from './catalog.js';

const HEADER = [
  '# Generated by `forgeprint build-codeowners`. Do not edit by hand.',
  '#',
  '# The root owner reviews everything: merge decisions stay with the core',
  '# maintainer (CLAUDE.md rule 12). Blueprint maintainers own their own folder',
  '# and approve changes to it; they do not merge.',
];

/**
 * Render `.github/CODEOWNERS` from the `maintainers` field of every manifest.
 * `coreMaintainer` owns the repository root, so that the Code Owners review
 * requirement always reaches them.
 */
export function renderCodeowners(blueprints: readonly Blueprint[], coreMaintainer: string): string {
  const lines = [...HEADER, '', `* @${coreMaintainer}`, ''];
  const owned = [...blueprints].sort((a, b) => a.slug.localeCompare(b.slug));
  if (owned.length > 0) {
    lines.push('# One line per blueprint, ordered by slug.');
    for (const blueprint of owned) {
      const owners = blueprint.manifest.maintainers.map((handle) => `@${handle}`).join(' ');
      lines.push(`/blueprints/${blueprint.slug}/ ${owners}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}
